macro generate_source(data)
<<-EOT
# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT !

module Emoji
  GENERATED_EMOJI_REGEX = /
    {{ data.id }}
  /x
end

EOT
end

macro create_source_file
  source = generate_source("{{ run("./data_loader.cr") }}")
  # Literal codepoints are hex-escaped, so every pipe is an alternation.
  File.write("./src/emoji/regex.cr", source.gsub("|", "|\n    "))
end

create_source_file
